eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1122/eureka/,http://localhost:1133/eureka/
server:
  port: 8084
spring:
    application:
      name: eurake-client
    restart:
      exclude:  static/**,public/**
      enabled:  true
    datasource:
      url: jdbc:mysql://192.168.19.249:3306/mynet?autoReconnect=true
      username: root
      password: san1546
## 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.example.eurakeclient.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

